General:
    GUILD_ID: 1045141276661653604 #The Guild ID the bot runs in
    TOKEN: "TOKEN" #The bot's token
    ACTIVITY: "playing" #playing, watching, or listening
    DOING_ACTIVITY: "Games" #What you would like the bot to be playing, watching, or listening to!
    STATUS: "online" #online, idle, dnd, or invisible

    EMBED_COLOR: "#BDBBFF" #The colors of the embeds
